### PR TITLE
Glitche on the library to fix #44

### LINKED ISSUE #44: Glitche on the library to fix
- [x] If you follow the below senario, the delete icon is truncated
- Click. to add new section to the page
- Click on one of the section
- Click on the X to close the popup opened
- Click again to add new section

Screen Shot 2022-06-17 at 3 28 23 PM

- [x] When you create a page, i should not have to refresh my page to have the edit option
- [x] When you open the wyzywig section, the back and X arrow should be above the Syziwyg name not on the same level

Screen Shot 2022-06-20 at 5 22 37 PM

- [x] When I edit a page there is an undefined error showing which is wrong

Screen Shot 2022-06-20 at 5 20 26 PM

- [x] Button to add a new section type behind the view page button, for example in hangmen:

Screen Shot 2022-06-20 at 5 20 12 PM

### PR DESCRIPTION
**Pull request by mahfouzhseineweev**

### CODE REVIEW

File: src/base/index.vue [hunk 1]
```diff
@@ -672,6 +677,25 @@ export default {
...
+            }
+          });
+          this.$set(this.displayVariations, this.activeVariation.pageName, {
+            name: this.activeVariation.pageName,
+            views: { ...views },
+          });
+          this.selectedVariation = this.activeVariation.pageName;
+          this.loading = false;
+          this.pageNotFound = false;
+          this.$emit("load", true);
```
Comment (jfayad) [inline src/base/index.vue:698]: Please add a comment in the code to explain what does this block of code solve

Comment (jfayad) [reply src/base/index.vue:699]: Saw the comment, but what's the point of loading sections for a page that was just created ? it will always be empty @mahfouzhseineweev

Comment (mahfouzhseineweev) [reply src/base/index.vue]: Indeed, I updated it
